# Generated by Django 6.0.6 on 2026-06-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=300)),
                ('isActive', models.CharField(choices=[('Y', 'Active'), ('N', 'Not Active')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Release Date')),
                ('cat_id', models.CharField(max_length=10)),
                ('format', models.CharField(choices=[('V', 'Vinyl'), ('CD', 'Compact Disc'), ('CS', 'Cassette Tape'), ('3C', '3-inch Compact Disc'), ('D', 'Digital Only')], default='V', max_length=2)),
                ('soldOut', models.CharField(choices=[('Y', 'Sold Out'), ('N', 'Currently Available')], default='Y', max_length=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
