# Generated by Django 6.0.6 on 2026-06-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.ImageField(default='Please Select An Image', upload_to='main_app/static/images/'),
        ),
    ]
