# Generated by Django 6.0.6 on 2026-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artist_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='isActive',
            field=models.CharField(choices=[('Y', 'Active Artist'), ('N', 'Not Currently Active')], default='Y', max_length=1),
        ),
    ]
