# Generated by Django 6.0.6 on 2026-06-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_release_options_alter_artist_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Artist Name', max_length=60),
        ),
    ]
