# Generated by Django 6.0.6 on 2026-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist_members_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='title',
            field=models.CharField(default='Record Title', max_length=100),
        ),
        migrations.AddField(
            model_name='release',
            name='tracks',
            field=models.TextField(default='Track List Here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='release',
            name='cat_id',
            field=models.CharField(default='Catalogue ID Number', max_length=10),
        ),
    ]
