# Generated by Django 6.0.6 on 2026-06-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_release_title_release_tracks_alter_release_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='img',
            field=models.ImageField(default='Please Select An Image', upload_to='main_app/static/images/releases'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img',
            field=models.ImageField(default='Please Select An Image', upload_to='main_app/static/images/artists'),
        ),
    ]
